### ISSUE TITLE
[Lexibanxify] task list

### ISSUE THREAD

**Issue by Wu-Urbanek** [lexibank/abrahammonpa#9]
This is a note for setting up a lexibank repository.
- [x] bibtex (resource.bib)
- [x] LICENSE, setup.py and test.py (copy and paste from another repository)
- [x] metadata.json
- [x] lexibank_abrahammonpa.py
- [x] orthography profile
